### PR TITLE
updated bitovi.com dropdown...i think. issue #228

### PR DESCRIPTION
**Pull request by julia-allyce**
https://github.com/bitovi/canjs.com/issues/228

### CODE REVIEW

**Comment by tomgreever** [comment]
Cool. Can you post a screen shot in the PR of the final result?

**Comment by daffl** [comment]
Unfortunately not right now because DocumentJS is broken.

**Comment by julia-allyce** [comment]
Yea...I tired just following the steps to update the static templates after they have been modified (running ./js scripts/doc.js), but could not get it to work either. I'm getting this error: 
`Error: Could not find or load main class org.mozilla.javascript.tools.shell.Main`

but in theory, the changes I made should just remove "Consulting" and add the links "Design" and "Development" in its place. All styling/formatting the same.

**Comment by justinbmeyer** [comment]
@julia-allyce ping me tomorrow about this.  The website is generated a very different way.

**Pull request closed without merging**
